### ISSUE TITLE
colour picker UI streamlining

### ISSUE THREAD

**Issue by petermeissner** [daattali/shinyjs#72]
I used the colour picker a lot the last two weeks - find it very handy. But I noticed some things I think can be improved to make working with it faster and more streamlined - in my opinion.

- the ***find R colour*** tab should be the default tab to come up : the *find any colour* tab seems to me to be just a not so handy and not so feature rich version *find R colour* 
- the ***find any colour*** tab should be dropped : there is nothing that *find any colour* can do, that *find R colour* cannot
- the default value for ***How many colours to show*** at the *find R colour* tab should be set to 16 : this maximizes the number of colours one can select from without forcing the user to scroll (why should one go with less - right?)

**Comment by daattali** [comment]
Hi Peter, thanks a lot for the feedback, I appreciate it. I think I'll keep it as is, unless more people tell me they agree with you, because I personally think it's better to have the default tab being a very simple one rather than one that has a lot going on (more intimidating).  

The "find any colour" tab *does* have functionality that the others don't. In the "find any colour" tab, you can select ANY RGB colour, while the other two tabs are restricted to only a subset of colours that are defined in R as named colours. For example, in the other two tabs, you won't be able to get a colour with HEX code "FFFFFE".

Regarding the number of colours on startup: I realized some people may want to initialize with more colours, and that's why you can call `colourPickerAddin(16)`. But that's making an assumption that the user will want to select many colours, and the vector they'll get back will contain 16 elements.  I prefer to not make assumptions and keep things as simple as possible, which in this case means to start with just one value by default.

I do appreciate your input and I definitely see where you're coming from! But I think the current defaults are good for the average person.

**Comment by petermeissner** [comment]
Hey, thanks for giving this some thoughts ... 

In regard to the third point `colourPickerAddin(16)` did not work for me but `colourPicker(16)` ... but it actually does not do the job - yes, I agree that the returned vector should be of length 1 by default, no assumptions. 

But what I actually meant is that on the second tab (which I love the most despite having no full RGB set of colours, 16 million colours is to much anyways) there is only one row of R-colours shown while the window (the size is fixed - right?) would support another row easily. So its not about picking more colours at once (usually I indeed need only one or two) but to be able to more quickly choose a color by beeing presented with a slightly larger palette.

**Comment by daattali** [comment]
Sorry for the slow reply, I'm at useR conference and the schedule here is packed with fun :)  

I completely understand what you mean now, yes, that makes more sense. The size of the addin is actually not fixed unfortunately. The width is going to stay mostly constant, but the height changes (even though I do explicitly tell RStudio what height I want, I did notice that it doesn't actually use that height, but uses a different height depending on my screen resolution). Are you on a desktop, or on a fairly large laptop?  Because on my two laptop, when there is a second row of colours, there is a vertical scrollbar.  That's why there's only one row!

**Comment by petermeissner** [comment]
Ah, useR - wish I were there - hmmmm ...

I got the impression, that dimensions are constant ... but if height
adjusts to screen size than it's no no-brainer anymore but a design
decision based on flavors of taste ... given that, I am undecided myself.


2016-06-28 9:11 GMT+02:00 Dean Attali <notifications@github.com>:

**Comment by daattali** [comment]
It's super fun here, and everybody is so friendly and awesome :)  You can
try it yourself - set the screen resolution to different dimensions and see
what happens?

---
http://deanattali.com

**Comment by petermeissner** [comment]
Yeah, I see it. Thanks for the effort and have fun at the useR.

2016-06-29 9:15 GMT+02:00 Dean Attali <notifications@github.com>:

> It's super fun here, and everybody is so friendly and awesome :) You can
> try it yourself - set the screen resolution to different dimensions and see
> what happens?
>
> ---
> http://deanattali.com
>
